### ISSUE TITLE
error when extending @nimbleways/eslint-config 

### ISSUE THREAD

**Issue by Armane-Pro** [nimbleways/eslint-config#1]
Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json » @nimbleways/eslint-config#overrides[0]': Class extends value undefined is not a constructor or null

**Comment by othmane-kinane-nw** [comment]
@abderrahmane-arache-nw can you retry with the newest version of the package ?

**Comment by Armane-Pro** [comment]
yes it works ✔✔✔,  thanks
